#version: '3.9'

services:
  upload-api:
    image: upload-api:latest  # Imagen local o del registry
    build:
      context: ../upload-api  # Ruta al código fuente del upload-api (opcional si quieres build local)
    ports:
      - "8000:8000"
    depends_on:
      - vector-db-api
    environment:
      - VECTOR_DB_API_URL=http://vector-db-api:8001
    networks:
      - vector-net

  vector-db-api:
    image: vector-db-api:latest  # Imagen local o del registry
    build:
      context: ../vector-db-api  # Ruta al código fuente del vector-db-api (opcional si quieres build local)
    ports:
      - "8001:8001"
    volumes:
      - vector-db-data:/app/chroma_db
    networks:
      - vector-net

  express-api:
    image: express-api:latest  # Imagen local o del registry
    build:
      context: ../express-api  # Ruta al código fuente del express-api (opcional si quieres build local)
    ports:
      - "3000:3000"
    depends_on:
      - upload-api
      - ollama
    environment:
      - FASTAPI_URL=http://vector-db-api:8001/query-vectors
      - OLLAMA_URL=http://ollama:11434/api/generate
    networks:
      - vector-net
  
  ollama:
    image: ollama/ollama:latest  # Imagen local o del registry)
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    entrypoint: >
      /bin/bash -c "
        ollama serve &
        sleep 2 &&
        ollama pull mistral &&
        tail -f /dev/null
      "
    networks:
      - vector-net

volumes:
  vector-db-data:
  ollama_data:

networks:
  vector-net:
    driver: bridge